version: "3.9"

services:
  # 🗄️ Database
  db:
    image: postgres:14-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 🚀 API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # 🔐 Auth service
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

# Persistent volume for DB
volumes:
  db-data:
