FROM node:24-alpine

WORKDIR /backend/auth

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3001

RUN addgroup -g 1001 -S nodejs && \
    adduser -S authuser -u 1001

RUN chown -R authuser:nodejs /backend/auth

USER authuser

CMD ["node", "server.js"]
