FROM node:24-alpine

WORKDIR /backend/api

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

RUN addgroup -g 1001 -S nodejs && \
    adduser -S apiuser -u 1001

RUN chown -R apiuser:nodejs /backend/api
USER apiuser

CMD ["node", "server.js"]
