name: Build and Test Backend

on:
  push:
    branches:
      - main

jobs:
  node-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api, auth]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.service }}-${{ hashFiles('${{ matrix.service }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.service }}-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        run: npm install --prefix ./${{ matrix.service }}

      - name: Run tests
        run: npm run test --prefix ./${{ matrix.service }}

      - name: Build project
        run: npm run build --prefix ./${{ matrix.service }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ matrix.service }}-image:latest
          docker build ./${{ matrix.service }} -t $IMAGE_NAME
